
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '59F8DE5280F84954E753C796FC571226'
    
_lr_action_items = {'Tap':([0,],[1,]),'Drip':([0,],[2,]),'Cling':([0,],[4,]),'Clink':([0,],[5,]),'Whack':([0,],[6,]),'$end':([1,2,3,4,5,6,],[-1,-4,0,-2,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> Tap','start',1,'p_start','PLYCreepyPoem.py',44),
  ('start -> Cling','start',1,'p_start','PLYCreepyPoem.py',45),
  ('start -> Clink','start',1,'p_start','PLYCreepyPoem.py',46),
  ('start -> Drip','start',1,'p_start','PLYCreepyPoem.py',47),
  ('start -> Whack','start',1,'p_start','PLYCreepyPoem.py',48),
]
